name: here_maps_atlas
description: An Atlas map provided by Here

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  atlas: 0.12.2
  image: ^2.1.19
  here_sdk:
    git:
      url: https://github.com/edsondiasalves/here_sdk.git
      ref: v4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4

flutter:
  uses-material-design: true